### ISSUE TITLE
Paste from Apple Notes is not working properly

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/AztecEditor-iOS#1066]
In iOS 11, copying and pasting (mostly) worked just fine. Thanks to @aerych, we were able to do a test:

![image from ios](https://user-images.githubusercontent.com/1123407/46746246-e1672380-cc6b-11e8-9679-d82e56e5405c.png).

In iOS 12, it turns the text into something like

>[HEAD] 
[META] 
[META] 
[TITLE] 
[META][STYLE] 
[BODY]

### Steps to reproduce the behavior

Creating a post with bold, italic, headings, and bulleted lists in Notes, then copy/pasting into Aztec seems to consistently result in this behaviour. 

##### Tested on iPhone X[S], iOS 12.1, Aztec (??? - version in WP 10.9)

**Comment by jkmassel** [comment]
Some examples of issues:
1363334-zen
1446382-zen

**Comment by SiobhyB** [comment]
I received another report of this issue in 1475004-z

The user provided the following screenshot of what the text looks like in their editor when pasted from Notes:

![img_4378](https://user-images.githubusercontent.com/2998162/46750449-e352d600-ccaf-11e8-8272-a758d00ed495.PNG)

**Comment by etoledom** [comment]
I'm testing with an iOS 11.1.2 device and it also get the same results.

Is it possible that the @aerych 's iOS 11 device is running an older version of the WordPress App?

**Comment by aerych** [comment]
Good thinking @etoledom.  My iPhone 6s had 10.8.1 installed.  After updating to 10.9 I can reproduce the behavior the user reported.  Sorry, I didn't realize I'd missed an update!

After pasting the content I copied from the Notes app I switched the editor to HTML mode and saw the following:
![img_8253](https://user-images.githubusercontent.com/1435271/46831851-23768f00-cd6a-11e8-8b5c-0307f42d6935.PNG)

Looks to me like the copied content is trying to be a proper HTML document but we're really only interested in what's inside the BODY tag.  So the unrecognized tags, including the BODY tag, are what's showing up.  The tags are stripped out when publishing but the CSS remains.

**Comment by etoledom** [comment]
Exactly! 
I've been trying to follow this issue. Since the `<body>` tag is unrecognized, all its content is replaced with the notation for unknown tag (`[BODY]`), but the original HTML remain untouched.

So far, I was able to make the system recognize the tags. I'm not sure yet how to keep the style, but I keep investigating this.

![img_092549283160-1](https://user-images.githubusercontent.com/9772967/46832360-32663d00-cd7c-11e8-90ba-260f1570f985.jpeg)

Thanks @aerych for the info!
I'll check out v10.8.1 and see how was this working there and what changes were made to the next version. I hope that helps.

**Comment by etoledom** [comment]
Just to confirm:
WP v10.8.1 on iOS 12 paste as it should. So it is definitely not an iOS version issue.

**Comment by SiobhyB** [comment]
This also came up in 1491452-z. (Noting so that I can follow up with user.)

**Comment by thehenrybyrd** [comment]
This appears to be broken again (or still).
We have a new report in 258889-zen, and I was able to reproduce in WPiOS 11.0.

<img src="https://user-images.githubusercontent.com/15107387/47614111-06002f80-daa3-11e8-973a-d0a3c5655e46.PNG" width="250"/>

To reproduce: 
Write some text (anything, doesn't have to have formatting) in the iOS Notes app.
Copy it, and paste into a new post in WPiOS 11.0.

Note: If, when pasting, you select "paste without formatting", the plain text is posted with no trouble. Ideally though, pasting should work as expected.

**Comment by etoledom** [comment]
Hi @thehenrybyrd !

This fix didn't make it to 11.0, but it's fixed in the current 11.1 Beta.

Apart of that, it is interesting to see that `Share your story here...` isn't hidden when you paste the text. Related to that is [this issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/10342).

Are you using iOS 11?

**Comment by donalirl** [comment]
The user from 258889-zen came back with their logs which shows the app version number as iOS 11.0 (11.0.0.2)

**Comment by thehenrybyrd** [comment]
@etoledom Thanks for clarifying! Glad to hear it's going into 11.1.

My phone is an iPhone SE, currently running iOS 10.3.3,  and running WPiOS 11.0.
The `Share your story here...` goes away if I scroll after pasting a multi-line something.
Happy to upgrade to iOS 11, or keep the older version if it's handy to test from multiple versions.
I can also do some more testing a post to that issue if you'd like.
