### ISSUE TITLE
How to use Editor using cocoapods installation: Instruction needed

### ISSUE THREAD

**Issue by mrramdhas** [wordpress-mobile/AztecEditor-iOS#1133]

**Comment by diegoreymendez** [comment]
This issue lacks context about what's been done, what been tried and what the problem is.

The generic response I can offer, given the lack of more information, is that you should check out the included demo App to see how Aztec is integrated to replicate it in your project.

If you have more specific questions, we'll need more detail to be able to help.

**Comment by mrramdhas** [comment]
If you choosing cocoapods: 
Step 1: 

  pod "WordPress-Aztec-iOS"
  pod "WordPress-Editor-iOS"
  pod 'Gridicons', :podspec => 'https://raw.github.com/Automattic/Gridicons-iOS/develop/Gridicons.podspec'

Step 2; 

Import EditorDemoController.swift file into your project and assign into your ViewController scene. 

Run and see magic
