### ISSUE TITLE
Crash on empty demo when click list/quote etc.. on newline

### ISSUE THREAD

**Issue by lincanli** [wordpress-mobile/AztecEditor-iOS#1158]
**Describe the bug**
many way to reproduce, but every way does indeed crash

1. open empty demo view controller
2. click list/qutoe
3. crash

second way to reproduce

1. open empty demo view controller
2. enter something
3. click list/qutoe
4. return to create new line
5. crash

...

**Smartphone (please complete the following information):**
Simulator iOS 12.2 iPhone 8 Plus

**Additional context**
I am using example project with Cocoapods, attached zip can run directly
[Example.zip](https://github.com/wordpress-mobile/AztecEditor-iOS/files/3017158/Example.zip)

Install via carthage can reproduce as well

Video:

![Untitled](https://user-images.githubusercontent.com/4588539/55147695-cfc5f980-5181-11e9-81e8-8ad795dde993.gif)

**Comment by shengyang998** [comment]
Same problem here

**Comment by SergioEstevao** [comment]
@lincanli Can you test this again on the latest version of the project? I don't think this is no longer happening.

**Comment by shahla00** [comment]
I couldn't reproduce this.

**Comment by CaseyYu1** [comment]
This issue is still replicable as of v1.19.8 with the exact same steps from the original post.

Simulator iPhone 8Plus on iOS 17. Xcode 14.3.1.

1. download v1.19.8 from the repository
2. open the example project included in the source code
3. run in simulator
4. select empty demo
4. without typing anything, click on List -> Ordered list
5. crash

![Screenshot 2023-08-25 at 12 49 25 PM](https://github.com/wordpress-mobile/AztecEditor-iOS/assets/143221866/c2b3fd83-f161-4411-a926-fa11311182bb)
