### ISSUE TITLE
Aztec iOS: Cursor placement in lists

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/AztecEditor-iOS#770]
1. Start a new unordered list.
2. Enter a few list items.
3. Press over the item N-1 and make some changes.
4. Press back over the latest item.

As a result, the cursor will jump from the last list item to the line below it. Any text I entered was entered on the new line, rather than being part of the list.

h/t @rachelmcr (Thanks for spotting this!)

**Comment by jleandroperez** [comment]
Closing as cannot repro.

Tested in iOS 11.1 / iPhone 7 / Aztec Develop.

**Comment by rachelmcr** [comment]
I tested this in iOS 11.0 / iPhone 7 simulator / Aztec Develop and I can still reproduce the issue, but I think I have a better idea of what's happening now. I noticed that as soon as I start creating a new list, there is an extra blank line after the last list item. Since I don't add that blank line myself I don't expect it to be there, and when I try to tap on the last item I'm not precise enough so the cursor ends up on the blank line instead of the last list item. (If I press and hold to get the magnifying glass, I can target the end of the last list item and successfully move the cursor there.)

If I switch to HTML mode and back to visual mode, that extra blank line disappears and I don't have any trouble. Ideally, the editor wouldn't add an extra line unexpectedly when I create a new list in my post, but this feels like a relatively minor issue.

**Comment by jleandroperez** [comment]
@rachelmcr Ahhhhhhh interesting. There's a very very good reason for that extra newline at the bottom: it's part of a workaround for an Apple SDK limitation.

Without it, it's not possible to render the last bullet. I'm afraid removing that is not possible, for us, at the moment.

Thanks for checking Rachel!!

**Comment by diegoreymendez** [comment]
@jleandroperez - Small detail on milestones: for issues that are simply closed, I'm no longer adding the milestone, to avoid them looking like something was released.

**Comment by jleandroperez** [comment]
Acknowledged! thanks for the clarification!
