### ISSUE TITLE
Not working on swift 4

### ISSUE THREAD

**Issue by atistank** [wordpress-mobile/AztecEditor-iOS#800]
I'm on Xcode 9.1 beta and swift 4

I run pod install AztecEditor-iOS on the my project, and then open.

But then when building, I get a lot of error and can't import Aztec module.

it not working for me, what should i do ?

**Comment by diegoreymendez** [comment]
Can you provide the build logs, or at least the errors you're seeing?

**Comment by atistank** [comment]
I get 93 syntax error in class AztecTextStorage after install coapod and open app in the first time. I think it not support for syntax swift 4.
<img width="1386" alt="screen shot 2017-11-02 at 9 18 50 pm" src="https://user-images.githubusercontent.com/23362696/32330699-746f7396-c013-11e7-98ad-8f0732aebc2e.png">


<img width="960" alt="screen shot 2017-11-02 at 9 16 01 pm" src="https://user-images.githubusercontent.com/23362696/32330575-22330d4a-c013-11e7-8177-06c7dc3afaf4.png">

**Comment by lixiaonan** [comment]
![image](https://user-images.githubusercontent.com/13104094/32377647-56411afc-c0e3-11e7-99d1-22f4f1becedb.png)

**Comment by diegoreymendez** [comment]
So for starters, I just [opened an enhancement ticket](https://github.com/wordpress-mobile/AztecEditor-iOS/issues/807) to migrate our code to Swift 4.  It's a high priority issue so it should happen sometime soon.

This, however, is not an issue on our end.

The problem you're seeing is due to the Swift version being incorrectly set for our pod by CocoaPods.  Here's a [link to the issue](https://github.com/CocoaPods/CocoaPods/issues/6791) in the CocoaPods repository.

If you follow that link you'll see that other developers are having the same problem, which can be solved by installing a post-installation hook such as this one in your Podfile:

```ruby
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            if ['WordPress-Aztec-iOS'].include? target.name
                target.build_configurations.each do |config|
                    config.build_settings['SWIFT_VERSION'] = '3.2'
                end
            end
        end
    end
```

I'm closing this, since it's a CocoaPods configuration issue.
