### ISSUE TITLE
Unexpected <p> tag when closing list

### ISSUE THREAD

**Issue by brbrr** [wordpress-mobile/AztecEditor-iOS#840]
### Expected behavior

when closing list there is no `<p>` tag is added:

```
<ol>
  <li>Q</li>
  <li>W</li>
  <li>E</li>
</ol>

```

### Actual behavior

`<p>` added after closed list. It disappears after toggling HTML view

```
<ol>
  <li>Q</li>
  <li>W</li>
  <li>E</li>
</ol>
<p></p>
```

### Steps to reproduce the behavior

![screencast 2017-11-27 19-42-43](https://user-images.githubusercontent.com/5654161/33267327-9f6d7114-d3ab-11e7-986f-04d09b79007d.gif)

**Comment by diegoreymendez** [comment]
@brbrr - In the example provided above, there's an empty line after the list, and the editor represents empty lines as paragraphs.

I'd say it's working as expected, and the way to prevent the empty paragraph from being there would be to remove the empty line from visual mode.

In order to prevent the empty paragraph from being added, after pressing enter twice, you should backspace once.

Unless we want to auto-strip P tags in certain scenarios, but that can be a slippery slope.

Thoughts @jleandroperez?

**Comment by brbrr** [comment]
Ah, right. I was thinking that it might be expected. Closing

**Comment by jleandroperez** [comment]
I'm late in here! but +1 to what @diegoreymendez said. It's the only way to preserve the bottom empty line.

Thanks @brbrr!!
