### ISSUE TITLE
Broken bouncing when scrolling all the way to the bottom.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/AztecEditor-iOS#905]
### Expected behavior

When scrolling the editor all the way to the bottom, the text view should bounce naturally.

### Actual behavior

The bouncing is broken.

### Steps to reproduce the behavior

1. Launch the empty editor.
2. Add content until you exceed the editor height, so you can scroll.
3. Scroll all the way to the bottom and check the text-view bouncing.

**Comment by venkatd333** [comment]
Expected behavior
When scrolling the editor all the way to the bottom, the text view bouncing is broken.

Actual behavior
It should bounce as usual.

Steps to reproduce the behavior
Launch the empty editor.
Add content until you exceed the editor height, so you can scroll.
Scroll all the way to the bottom and check the text-view bouncing.
